var animal = 'lion';
var number1 = 5;
var number2 = 10;
console.log(animal === 'lion');
console.log(animal === 'elephant');
console.log(animal !== 'tiger');
console.log(animal !== 'lion');
console.log(animal.indexOf('li') !== -1);
console.log(animal.indexOf('li') === 0);
console.log(animal.length > 4);
console.log(animal.toLowerCase() === 'lion');
console.log(animal.charAt(2) === 'o');
console.log(number1 < number2);
console.log(number1 >= 5);
